### ISSUE TITLE
Collection Log Pop-up not showing

### ISSUE THREAD

**Issue by KurtisWhiteman** [CarlOmega/examine-log#6] opened 2024-09-26 05:33 UTC
I can see that the same issue was closed and merged last week.
I closed and opened RuneLite today after the new Varlamore update so my runelite is up to date. I also uninstalled and reinstalled dexamine too. Upon examining anything I never get a pop-up and never have. I even went out of my way to find some obscure thing I haven't examined possibly every or even since installing the plugin(again, too). Friends either do get the pop-up too or do not with nothing discernably different between our setups.

I have no idea what may or may not cause the issue. I don't have any "collection log" related plugins that might effect the pop-up specifically like the C Engineer one. Only the ones like "Collection Log Luck" and "Dink".

**Comment by CarlOmega** [comment] 2024-09-26 06:08
The original issue was due to different resizable modes and how the trigger for the popup was being run. But I can investigate this if this is still happening for you. Hard without being able to reproduce it is all but will see what I can find.

**Comment by KurtisWhiteman** [comment] 2024-09-26 06:11
I play in classic fixed if that helps. I could also run runelite with intellij in debug mode if you can give me a hint as for what to lookout for?

**Comment by KurtisWhiteman** [comment] 2024-09-26 06:37
After further testing. The pop-up seems to only work in resizable modern. Not classic fixed or classic resizable.

**Comment by CarlOmega** [comment] 2024-09-27 04:07
Fixed now should come in with the next release.

**Comment by CarlOmega** [comment] 2024-10-12 20:38
Should be fixed now. Let me know if there is any other weird bugs. Im looking at redesigning the collection log interface and keen to hear what people want.

**Closed** 2024-10-12 20:38 UTC
