### ISSUE TITLE
Collection Log progress reset? 

### ISSUE THREAD

**Issue by santzuu** [CarlOmega/examine-log#5] opened 2024-09-22 11:20 UTC
Title. I grinded quite a bit of examines on the log, only to find out that all of my progress had been wiped and reset after logging out. Seems that also teleporting around in the world it reset my progress for a second time while playing lol. I got confused since I got 3 times the notification for the exact same item (and no, its not the case like different "rocks" or trees have slightly different examine texts or different items like different ores have same examine text) its the exact same object, exaclty same spot giving the notification again that its a new examine since the plugin seems to wipe my progress for some reason. Kinda annoying and I dont really want to keep examining stuff anymore if it gets wiped like that. Any way to restore the progress I had etc.? Or way to fix the issue tyvm

**Comment by santzuu** [comment] 2024-09-22 11:24
Re-edit: I've tried it again. Definitely logging out is the issue. I examined multiple things again, I logged out --> logged back in --> examine log is completely empty.... This is quite dissapointing since this bug essentially defeats the entire purpose of the plugin :/ hopefully it can be fixed soon!

**Comment by santzuu** [comment] 2024-09-22 11:44
Ok - after having tested a bit with trial and error with the plugin and one of my clanmates helping with reading actually the code of the plugin - it seems that the plugin ONLY saves when you: shutdown the client (this did NOT WORK for me at least) or B) close the plugin (this did work). Closing the plugin aka. turning it off, and then logging out, and logging back in and turning it back on worked.... kinda.... but not really lol. It seemed to pull some date from my earlier examine set which was then reset when I logged out - the save thing is definitely bugged BUT the plugin seems to be able to still store somehow your examine data somewhere even thou you log out and it seems to be "erased" since It did "restore" some of my examines with the trial of closing the plugin and then logging out.

**Comment by CarlOmega** [comment] 2024-09-22 22:06
So the problem is known and a duplicate of [this issue](https://github.com/CarlOmega/examine-log/issues/2). The fix is waiting for the runelite team. 

The problem occurs when the logs are unable to load on startup. I moved away from using account name to something more reliable. 

The shutdown code you are mentioning isnt live atm but a failsafe I added along side it. 

The logs save anytime you get a new log as well as if you close or shutdown to ensure they save. The new changes will also only save if your logs are loaded correctly.

**Comment by aslycow** [comment] 2024-10-02 04:28
I'm finding this issue as well, I lose all logged examines if I close RuneLite. 

Awesome idea, I've come to really enjoy passively examining things!

**Comment by aslycow** [comment] 2024-10-05 15:49
Also if possible, is there any way to recover a lost log? I've been keeping things running by turning the plugin off before I log out, then turning it back on when I log back in, but I missed it once and lost 80-90 examines, including some quest items I won't be able to examine anymore :((

**Comment by CarlOmega** [comment] 2024-10-06 00:06
I do apologise for the delay on the update. Unfortunately not much can be done to recover lost logs. I am looking at reworking some parts as I want a better way to view them in the collection log. I want to show the npc model and object model instead of place holders. I also have a way now to determine how many logs there are in total and might start creating a list of examines that are quest only. There is much more that needs to go into the plugin and unfortunately I am busy busy with full time work. 

Appreciate your feedback but my hands are tied and I dont want to do anything dodgey, so I need to wait for the RL team to have time to review.

**Comment by aslycow** [comment] 2024-10-06 04:32
No worries my dude! Looking forward to seeing more improvements, I'm having
a lot of fun with it as-is anyways, trying to see if I can make a YT series
about it. Best of luck with your irl job and any other coding endeavors!

**Comment by CarlOmega** [comment] 2024-10-12 20:36
Should be live now. Let me know if there is any problems and super sorry for the delay. Im working on cataloging and redesigning the way you view them. Want to take inspiration from an original Pokedex. 

@aslycow keep me posted on the YT series and if there is anything I can do to help enable the experience. If you are interested in another unique mode check out my other plugin "Slotless". Start off with all equipment and inventory locked and for every 10QP you can choose a slot to unlock. It's been very fun playing it.

**Closed** 2024-10-12 20:37 UTC
