### ISSUE TITLE
Examine log disappears when relaunching game

### ISSUE THREAD

**Issue by mike-solomon** [CarlOmega/examine-log#2] opened 2024-09-18 23:28 UTC
If I close out of RuneLite and launch the game again - my examine log disappears. 

I'm using the Jagex launcher. If there's other information I can provide to help with debugging please let me know :) 

![image](https://github.com/user-attachments/assets/c0435012-9eb0-4358-9d14-6ff04a74bb42)

**Comment by CarlOmega** [comment] 2024-09-19 00:18
I'll investigate today. I have a suspicion that its how it handles startup and loading your logs but don't think this will be too challenging to address.

**Comment by jbcaud** [comment] 2024-09-20 05:14
Took a look at this @CarlOmega and it seems like it is due to loading logs immediately on startup when at the title screen. Since the player can't be retrieved at that time it doesn't make it past the first conditional. I moved the loading of the pages to the method that adds the examine widgets to the clog and it worked. I think moving it somewhere in that process makes sense, since the data doesn't need to be loaded until that point anyway and writing the log to disk happens in a different process. Thoughts?

**Comment by CarlOmega** [comment] 2024-09-20 05:21
@jbcaud thought this may have been the case. Been flat out with work so barely had time to look into it. I suspect if this is the case then most likely most if not all the logs are being reset after closing RL. I can update the code this afternoon. But the RL team may take some time to review it. I should have tested more but was eager to release.

**Comment by CarlOmega** [comment] 2024-09-20 05:27
Could always just load it from the game state change [GameStateChanged](https://static.runelite.net/api/runelite-api/net/runelite/api/events/GameStateChanged.html).

**Comment by jbcaud** [comment] 2024-09-20 05:31
I can confirm the logs still persist on my disk on logout/reloading RL so that should be fine. It's just that they are only being loaded once and that is on startup, which seems to only occur on the title screen. GameStateChanged seems like a good solution since it has the LOGGED_IN state.

**Comment by jbcaud** [comment] 2024-09-20 06:33
Okay after playing with it and searching through the RuneLite discord, it seems like the LOGGED_IN state doesn't work either because the vast majority of data is loaded 1 game tick after the game initializes. After debugging for a bit I found that it doesn't have the player name when this fires either.

Through all the conversations I saw in the discord, it seems like the most common solution is to have a boolean set on LOGGED_IN, then check that boolean in onGameTick and perform actions based on that. See [this](https://github.com/wise-old-man/wiseoldman-runelite-plugin/blob/7a20f8fdd09a19836a863ef9009ed8e8657473cf/src/main/java/net/wiseoldman/WomUtilsPlugin.java#L982) for an example.

**Comment by CarlOmega** [comment] 2024-09-20 06:45
I've done this as I would assume people want to keep their logs even after switching names. Seems to be a more reliable approach. It will also try to load the logs before saving and wont save unless there is a profile to save to.  
```java
	@Subscribe
	public void onGameStateChanged(GameStateChanged gameStateChanged) {
		if (gameStateChanged.getGameState() != GameState.LOGGED_IN) {
			return;
		}

		String profileKey = configManager.getRSProfileKey();
		loadExamineLogsFromDisk(profileKey);
	}
```

**Comment by jbcaud** [comment] 2024-09-20 06:56
Keeping the same log across accounts is interesting, I was wondering earlier if that was a feature that would be wanted. Could also be a config feature in the future if some wanted to keep their account logs separate from each other. In any case, that solution makes sense.

**Comment by CarlOmega** [comment] 2024-09-20 07:00
Closing this as [commit 6a25ed1](https://github.com/CarlOmega/examine-log/commit/6a25ed1c072d70ece21fd38cb136ccee89024ad2) should fix it.

**Closed by CarlOmega** 2024-09-20 07:00 UTC
